services:
  nginx_webdav:
#    image: sfuhrm/docker-nginx-webdav # comment out this line if you are building from source.
    # comment out these lines if you are just pulling the docker hub image.
    build:
      context: .
      args:
        NGINX_UID: 100
        NGINX_GID: 101
#    ports: # enable this if you are not using reverse proxy, otherwise leave commented out
#      - "80:80"
    container_name: webdav
    volumes:
      - "/path/to/your/share:/media/data"
